joint_limits_abs:
- [-90, 90]
- [0, 180]
- [-45, 135]
joint_limits_rel:
- [-90, 90]
- [-30, 80]
- [-45, 70]
link_lengths: [250, 250, 50]
q_offset: [90, 60, 0]
workspace_file: "config/qbot_workspace.pkl"